server:
  port: 8081
  version: 'v1'

spring:
  application:
    name: log-consumer
  data:
    mongodb:
      host: localhost
      port: 27017
      database: logger-db
  kafka:
    bootstrap-servers: kafka:9092
    client-id: log-project-client
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer