server:
  port: 8080
  version: 'v1'

spring:
  application:
    name: log-listener
  kafka:
    bootstrap-servers: kafka:9092
    client-id: log-project-client
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

log:
  file:
    path: /app/logs/log.txt
    last-read-position:
      file:
        path: /app/logs/log-remember.txt